authorName: Haim
experimentName: NNI_Just_Values_and_Graph_Structure_Cirrhosis
trialConcurrency: 1   # max GPUs to use simultaneously.
maxExecDuration: 100h
maxTrialNum: 99999
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: nni_search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python main_for_three_models.py --task_number 3 --dataset cirrhosis --device_num 0
  codeDir: .
  gpuNum: 2
localConfig:
  useActiveGpu: true