authorName: Haim
experimentName: NNI_Concat_Graph_and_Values_TCR_300
trialConcurrency: 1   # max GPUs to use simultaneously.
maxExecDuration: 48h
maxTrialNum: 99999
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: nni_search_space_tcr.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python new_main.py --nni 1 --task_number 7 --dataset tcr --samples 300 --device_num 2
  codeDir: ..
  gpuNum: 2
localConfig:
  useActiveGpu: true