authorName: Haim
experimentName: NNI_Yoram_Attention_Cirrhosis
trialConcurrency: 1   # max GPUs to use simultaneously.
maxExecDuration: 24h
maxTrialNum: 99999
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: nni_search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python new_main.py --nni 1 --task_number 6 --dataset Cirrhosis --device_num 0
  codeDir: ..
  gpuNum: 2
localConfig:
  useActiveGpu: true