authorName: Haim
experimentName: NNI_Just_Values_and_Graph_Structure_TCR
trialConcurrency: 1   # max GPUs to use simultaneously.
maxExecDuration: 48h
maxTrialNum: 99999
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: nni_search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python nni_new_main.py --nni 1 --task_number 3 --dataset tcr --device_num 3
  codeDir: ..
  gpuNum: 2
localConfig:
  useActiveGpu: true